name: Build/Test/Deploy
on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - run: |
          git config user.name "CI Bot"
          git config user.email "ci@invalid.invalid"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        with:
          BRANCH: gh-pages
          FOLDER: .vuepress/dist/
          CLEAN: true
          GIT-CONFIG-NAME: "CI Bot"
          GIT-CONFIG-EMAIL: "ci@invalid.invalid"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint-ci
